OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

PeerOrgs:
  - Name: Org1
    Domain: org1.example.com

    Template:
      Count: 3
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.example.com

    Template:
      Count: 3
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.example.com

    Template:
      Count: 3
    Users:
      Count: 1