# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:
  zookeeper.example.com:
    container_name: zookeeper.example.com
    extends:
      file: ./base/peer-base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - basic

  zookeeper1.example.com:
    container_name: zookeeper1.example.com
    extends:
      file: ./base/peer-base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=2
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888
    networks:
      - basic

  zookeeper2.example.com:
    container_name: zookeeper2.example.com
    extends:
      file: ./base/peer-base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=3
    ports:
      - 22181:2181
      - 22888:2888
      - 23888:3888
    networks:
      - basic

  kafka.example.com:
    container_name: kafka.example.com
    extends:
      file: ./base/peer-base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=1
    ports:
      - 9092:9092
      - 9093:9093
    networks:
      - basic
    depends_on:
      - zookeeper.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com

  kafka1.example.com:
    container_name: kafka1.example.com
    extends:
      file: ./base/peer-base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=2
    ports:
      - 10092:9092
      - 10093:9093
    networks:
     - basic
    depends_on:
      - zookeeper.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com

  kafka2.example.com:
    container_name: kafka2.example.com
    extends:
      file: ./base/peer-base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=3
    ports:
      - 11092:9092
      - 11093:9093
    networks:
      - basic
    depends_on:
      - zookeeper.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com

  kafka3.example.com:
    container_name: kafka3.example.com
    extends:
      file: ./base/peer-base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=4
    ports:
      - 12092:9092
      - 12093:9093
    networks:
      - basic
    depends_on:
      - zookeeper.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com