version: '3'

services:
  ipfs_node2:
    container_name: ipfs_node2
    image: ipfs/go-ipfs:release
    restart: always
    ports:
      - 4002:4001
      - 0.0.0.0:5002:5001
      - 0.0.0.0:8081:8080
    volumes:
      - ./compose/ipfs_node2/staging:/export
      - ./compose/ipfs_node2/data:/data/ipfs